# upload Pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload
  labels:
    app: upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
    spec:
      containers:
      - name: upload
        image: hongyeee/khu_2021105662:upload
        ports:
        - containerPort: 8888
          protocol: TCP

        volumeMounts:
        - name: test-vol-1
          mountPath: /app/temp
      volumes:
        - name: test-vol-1
          persistentVolumeClaim:
            claimName: share-volume
---
# show Pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: show
  labels:
    app: show
spec:
  replicas: 1
  selector:
    matchLabels:
      app: show
  template:
    metadata:
      labels:
        app: show
    spec:
      containers:
      - name: show
        image: hongyeee/khu_2021105662:show
        ports:
        - containerPort: 8889
          protocol: TCP

        volumeMounts:
        - name: test-vol-1
          mountPath: /app2/temp
      volumes:
        - name: test-vol-1
          persistentVolumeClaim:
            claimName: share-volume
---
apiVersion: v1
kind: Service
metadata:
  name: service-1
spec:
  type: NodePort
  selector:
    app: upload
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888
    nodePort: 30036
---
apiVersion: v1
kind: Service
metadata:
  name: service-2
spec:
  type: NodePort
  selector:
    app: show
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8889
    nodePort: 30037
